name: serpapi_price_tool_sample
description: "A sample tool to test basic function of serpapi."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  dio: ^5.9.0
  dropdown_button2: ^2.3.9
  fl_chart: ^1.1.1
  decimal: ^3.2.4
  logging: ^1.3.0
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/josefin/JosefinSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/josefin/JosefinSans-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/josefin/JosefinSans-Light.ttf
          weight: 400
        - asset: assets/fonts/josefin/JosefinSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/josefin/JosefinSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/josefin/JosefinSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/josefin/JosefinSans-Bold.ttf
          weight: 800

    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/noto/NotoSansSC-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto/NotoSansSC-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto/NotoSansSC-Light.ttf
          weight: 300
        - asset: assets/fonts/noto/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto/NotoSansSC-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto/NotoSansSC-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto/NotoSansSC-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto/NotoSansSC-Black.ttf
          weight: 900